<?php
$API_LIST = array(
    array(
        'type' => 'api',
        'version' => '0.9',
        'method' => 'GET',
        'resource' => 'publickey',
        'authorize' => 'N',
        'module' => '',
        'function' => 'api_get_rsa_public_key',
    ),
    array(
        'type' => 'api',
        'version' => '0.9',
        'method' => 'GET',
        'resource' => 'master',
        'authorize' => 'Y',
        'module' => 'master/master.api.php',
        'function' => 'api_get_sammast',
    ),
    array(
        'type' => 'api',
        'version' => '0.9',
        'method' => 'GET',
        'resource' => 'clientversion',
        'authorize' => 'N',
        'module' => '',
        'function' => 'api_get_client_version',
    ),
    array(
        'type' => 'api',
        'version' => '0.9',
        'method' => 'GET',
        'resource' => 'data',
        'authorize' => 'Y',
        'module' => 'trans/trans.api.php',
        'function' => 'api_get_samdata',
    ),
    array(
        'type' => 'api',
        'version' => '0.9',
        'method' => 'POST',
        'resource' => 'data',
        'authorize' => 'Y',
        'module' => 'trans/trans.api.php',
        'function' => 'api_create_samdata',
    ),
    array(
        'type' => 'api',
        'version' => '0.9',
        'method' => 'DELETE',
        'resource' => 'data',
        'authorize' => 'Y',
        'module' => 'trans/trans.api.php',
        'function' => 'api_delete_samdata',
    ),
);
